apiVersion: v1
kind: Service
metadata:
  name: suite-command-center-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: suite-command-center-api
spec:
  selector:
    app: suite-command-center-api
  ports:
    - name: http
      port: {{ default 80 (get (get (get .Values "api") "service") "port") }}
      targetPort: {{ default 8000 (get (get (get .Values "api") "service") "targetPort") }}
