{{- $sa := .Values.serviceAccount | default dict -}}
{{- $create := (get $sa "create") | default true -}}
{{- if $create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ (get $sa "name") | default (printf "%s" (include "suite-command-center.fullname" .)) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
