apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: command-center
  namespace: suite
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`command-center.suite.home.arpa`)
      kind: Rule
      priority: 1
      services:
        - name: suite-command-center-ui
          port: 80
  tls: {}
