apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: command-center-api
  namespace: suite
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`command-center.suite.home.arpa`) && PathPrefix(`/v1`)
      kind: Rule
      middlewares:
        - name: command-center-strip-v1
      services:
        - name: suite-command-center-api
          port: 80
