apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: suite-command-center
  namespace: suite
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`command-center.suite.home.arpa`) && PathPrefix(`/api`)
      kind: Rule
      middlewares:
        - name: strip-api
      services:
        - name: suite-command-center-api-shim
          port: 80

    - match: Host(`command-center.suite.home.arpa`)
      kind: Rule
      services:
        - name: suite-command-center-ui
          port: 80
  tls: {}
