apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-traefik-to-api-shim
  namespace: suite
spec:
  podSelector:
    matchLabels:
      app: suite-command-center-api-shim
  policyTypes:
    - Ingress
  ingress:
    - from:
        # k3s Traefik is usually here
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
        # in case you installed Traefik into its own ns
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
      ports:
        - protocol: TCP
          port: 8000
