apiVersion: v1
kind: Service
metadata:
  name: suite-command-center-api
  namespace: suite
  labels:
    app: suite-command-center-api
spec:
  type: ClusterIP
  selector:
    app: suite-command-center-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
