apiVersion: apps/v1
kind: Deployment
metadata:
  name: suite-command-center-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suite-command-center-api
  template:
    metadata:
      labels:
        app: suite-command-center-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: suite-command-center-api
spec:
  selector:
    app: suite-command-center-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
