apiVersion: v1
kind: Service
metadata:
  name: suite-command-center-api
  namespace: suite
spec:
  selector:
    app: suite-command-center-api-shim
  ports:
    - name: http
      port: 80
      targetPort: 8000
