apiVersion: v1
kind: Service
metadata:
  name: suite-command-center-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: suite-command-center-api
spec:
  selector:
    app: suite-command-center-api
  ports:
    - name: http
      port: {{ .Values.api.service.port | default 80 | default 80 }}
      targetPort: {{ .Values.api.service.targetPort | default 8000 }}
