{{- $sa := .Values.serviceAccount | default dict -}}
{{- $create := true -}}
{{- if hasKey $sa "create" -}}
{{- $create = $sa.create -}}
{{- end -}}
{{- if $create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ (get $sa "name" | default "suite-command-center-api") }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: suite-command-center-api
{{- end }}
