{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default "suite-command-center-api" }}
  namespace: {{ .Release.Namespace }}
{{- end }}
