{{- $sa := .Values.serviceAccount | default dict -}}
{{- if (get $sa "create" | default true) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ (get $sa "name" | default "suite-command-center-api") }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: suite-command-center-api
{{- end }}
