apiVersion: apps/v1
kind: Deployment
metadata:
  name: suite-command-center-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: suite-command-center-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suite-command-center-ui
  template:
    metadata:
      labels:
        app: suite-command-center-ui
    spec:
      nodeSelector:
        suite.home.arpa/display: "true"
      containers:
        - name: ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.ui.port | default 80 }}
