apiVersion: v1
kind: Service
metadata:
  name: suite-command-center-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: suite-command-center-ui
spec:
  type: ClusterIP
  selector:
    app: suite-command-center-ui
  ports:
    - name: http
      port: {{ .Values.service.uiPort | default 80 }}
      targetPort: {{ .Values.ui.port | default 80 }}
      protocol: TCP
