apiVersion: v1
kind: Service
metadata:
  name: suite-command-center-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: suite-command-center-ui
spec:
  type: {{ .Values.ui.service.type | default "ClusterIP" }}
  selector:
    app: suite-command-center-ui
  ports:
    - name: http
      port: {{ .Values.ui.service.port | default 80 }}
      targetPort: {{ .Values.ui.service.targetPort | default 3000 }}
