apiVersion: v1
kind: Service
metadata:
  name: suite-command-center-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: suite-command-center-ui
spec:
  selector:
    app: suite-command-center-ui
  ports:
    - name: http
      port: 80
      targetPort: http
