apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Flux controllers + bootstrap bits
  - ./flux-system

  # Apps (include each app ONCE)
  - ../../apps/suite/command-center
