ui:
  repository: 192.168.50.248:5000/suite-command-center-ui
  tag: 11b4e70-155348
 # tag: 20260109-bossmode
  env:
    NEXT_PUBLIC_UI_THEME: "boss"
    NEXT_PUBLIC_ENABLE_MOTION: "true"
    NEXT_PUBLIC_ENABLE_CARDS: "true"

api:
  repository: 192.168.50.248:5000/suite-command-center-api
  tag: latest
