# suite-command-center Helm values

api:
  image:
    repository: 192.168.50.248:5000/suite-command-center-api
    tag: latest
    pullPolicy: IfNotPresent

ui:
  image:
    repository: 192.168.50.248:5000/suite-command-center-ui
    tag: latest
    pullPolicy: IfNotPresent
