replicas:
  api: 1
  ui: 1

image:
  repository: registry.suite.home.arpa:5000/suite-command-center-api
  tag: latest

uiImage:
  repository: registry.suite.home.arpa:5000/suite-command-center-ui
  tag: latest

service:
  port: 80

ingress:
  enabled: false

serviceAccount:
  create: true
  name: suite-command-center-api

ui:
  service:
    targetPort: 3000
ui:
  service:
    targetPort: 3000
