api:
  image:
    repository: registry.suite.home.arpa:5000/suite-command-center-api
    tag: latest
  port: 8000

ui:
  image:
    repository: registry.suite.home.arpa:5000/suite-command-center-ui
    tag: latest
  port: 80

service:
  apiPort: 80
  uiPort: 80
