apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../apps/observe/monitoring
  - ../../../../apps/observe/uptime
  - ../../../../apps/observe/grafana-ingress.yaml
