apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: clm
  namespace: suite
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`clm.allenwmoorejr.org`)
      kind: Rule
      services:
        - name: clm
          port: 80
  tls:
    secretName: clm-tls
