apiVersion: v1
kind: Service
metadata:
  name: clm
  namespace: {{ .Release.Namespace }}
  labels:
    app: clm
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: {{ .Values.ui.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: clm
